config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'utilisateurs', path_names: {
    sign_in: 'connexion',
    sign_up: 'inscription'
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, path: 'produits'


  resource :cart, only: [:show] do
    post 'add_article_to_cart', on: :collection
    delete 'remove_article_from_cart', on: :collection  # Suppression d'un article spécifique du panier
    delete 'clear_cart', on: :collection 
  end

scope '/checkout' do
  post 'create', to: 'checkout#create', as: 'checkout_create'
  get 'success', to: 'checkout#success', as: 'checkout_success'
  get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get '/contact', to: 'static_pages#contact'

  resources :profiles, only: [:show]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    if params[:id].to_i == current_user.id
      @user = current_user
      @orders = @user.orders
    else
      redirect_to root_path, alert: "Accès non autorisé."
    end
  end



end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<%= javascript_include_tag 'item' %>

<%= render 'layouts/navbar' %>

<div class="body-profile">

  <h2>Mon profil</h2>
  
  <h3>Mes infos</h3>

  <div class="my-info">
     <div class="email-info-container">
      <p><%= current_user.email %></p>
    </div>
      <%= button_to "Modifier", edit_user_registration_path(current_user), method: :get, class: "btn-primary" %>
  </div>
  <br><br><br>

  <h3>Mes commandes</h3>

  <div class="orders-containers">

    <div class="column-name-line">
      <p class="column-name">Date d'achat</p>
      <p class="column-name">N° de commande</p>
      <p class="column-name">Status</p>
      <p class="column-name price-element">Prix total</p>
    </div>

   
   
    <% if @orders.any? %>
  <% @orders.reverse.each do |order| %>
  <div class="order-info-line" onclick="toggleOrderItems(this)">
    <p class="order-tab"><%= order.created_at.strftime("%d/%m/%Y") %></p>
    <p class="order-tab"><%= order.stripe_customer_id %></p>
    <p class="order-tab"><%= order.status %></p>
    <p class="order-tab"><%= number_to_currency(order.total_price, unit: "€") %></p>
  </div>
  
  <div class="list-order-item" style="display: none;">
  <div class="infotext">
    <p class="infotextname">Article</p>
    <p class="infotextname">Quantité</p>
    <p class="infotextname">Prix</p>
    </div>
    <div class="traitsep"></div>
    <% order.order_items.each do |item| %>
    <div class="lineitem">
      <p class="infoitemorder"><%= item.article.name %></p>
       <p class="infoitemorder"><%= item.quantity %></p>
        <p class="infoitemorder"><%= number_to_currency(item.price, unit: "€") %></p>
        </div>
    <% end %>
  </div>

 
<% end %>

      

    <div class="no-order-yet">
    <% else %>
      <p class="no-order">Vous n'avez pas encore passé votre première commande.</p>
    <% end %>
    </div>
    </div>
      <div class="section-admin">
  <% if @current_user.is_admin %>
    <h3>Section Admin</h3>
    <%= button_to "Ajouter un article", new_article_path, method: :get, class: "btn-primary-add" %>
    <br><br><br>
    <% end %>
  </div>
  
  


</div>

<%= render 'layouts/footer' %>