config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'utilisateurs', path_names: {
    sign_in: 'connexion',
    sign_up: 'inscription'
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, path: 'produits'


  resource :cart, only: [:show] do
    post 'add_article_to_cart', on: :collection
    delete 'remove_article_from_cart', on: :collection  # Suppression d'un article spécifique du panier
    delete 'clear_cart', on: :collection 
  end

scope '/checkout' do
  post 'create', to: 'checkout#create', as: 'checkout_create'
  get 'success', to: 'checkout#success', as: 'checkout_success'
  get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get '/contact', to: 'static_pages#contact'

  resources :profiles, only: [:show]
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :generate_slug  # Génère un slug avant de sauvegarder
  has_one_attached :avatar

  has_many :cart_items, dependent: :destroy # Articles ajoutés à des paniers.
  has_many :carts, through: :cart_items  # Les paniers contenant cet article.
  has_many :order_items                  # Articles achetés via des commandes.
  has_many :orders, through: :order_items # Commandes ayant cet article.

  
  def generate_slug # Génère un slug "mon-titre-d-article" à partir du titre si le slug est vide
    self.slug = name.parameterize if slug.blank? 
  end

  
  def to_param  # Rails utilisera le slug au lieu de l'id dans les URLs
    slug  
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_admin, only: [:new, :create, :destroy]

    def index
      @articles = Article.page(params[:page]).per(6)
    end
  
    def show
      @article = Article.find_by!(slug: params[:id]) || Article.find(params[:id]) # Recherche par slug mais si aucun slug match, il cherche par id.
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to article_path(@article), notice: "Produit créé avec succès !"
      else
        render :new, alert: "Une erreur s'est produite."
      end
    end

    def destroy
      @article = Article.find_by!(slug: params[:id]) || Article.find(params[:id])
      @article.cart_items.destroy_all
      @article.destroy
      redirect_to articles_path, notice: "Produit supprimé avec succès !"
    end

    private 

    def article_params
      params.require(:article).permit(:name, :description, :price, :avatar)
    end

    def check_admin
      unless current_user.is_admin
        redirect_to root_path, alert: "Vous n'êtes pas autorisé à effectuer cette action."
      end
    end

end
  

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/index.html.erb
<div class="jumbotron">
  <%= render 'layouts/navbar' %>
  <div class="container_jumbo">
    <div class="text-content">
      <h1>The Market Cat</h1>
      <h3>"Des chats qui ne griffent pas..."</h3>
    </div>
    <div class="image-container">
      <%= image_tag("imageJumbo.png", alt: "Cat", class: "img_jumbo") %>
    </div>
  </div>
</div>

<div class="articles-container">
  <h2>Articles :</h2>

  <turbo-frame id="articles">
    <div class="grid" id="articles-list">
      <% @articles.reverse.each do |article| %>
        <div class="cardd">
          <div class="article_img">
            <div class="imghover">
            <%= link_to article_path(article), class: "btn_article", data: { turbo_frame: "_top" } do %>
                  <%if article.avatar.attached?%>
                  <%= image_tag article.avatar, alt: 'avatar', class: 'img_article'%>
                  <%else%>
                  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
                  <%end%>
               <% end %>
               </div>
              <div class="border_article">
                
                <div class="article_name">
                  <div>
                  <p class="text-article-index"><%= article.name %></p> <br>
                  <p class="price-article-index"><%= number_to_currency(article.price, unit: " ") %>€</p>
                  </div>
                   <div>
                  
                   <% if current_user %>
                  <%= button_to add_article_to_cart_cart_path(article_id: article), method: :post, class: 'addcartindex', id: "add_to_cart_#{article.id}" do %>
                    <%= image_tag('panier.png', class: 'addcarticon', id: "image_#{article.id}") %>
                  <% end %>
                  <% end %>
                   </div>
                </div>
              </div>

          </div>
        </div>
      <% end %>

      <div class="block_card">
        <div id="pagination">
          <%= paginate @articles, remote: true %>
        </div>
      </div>
    </div>
  </turbo-frame>
</div>

<%= render 'layouts/footer' %>
</div>

app/views/articles/new.html.erb
<%=render 'layouts/navbar' %>
<div class="cont-add-admin">
<h2>Ajouter un nouvel article:</h2>

<%= form_with model: @article, local: true do |form| %>


<div class="form-group">
  <%= form.label :name, "Nom de l'article", class: "infoadd" %>
  </br>
  <%= form.text_field :name,placeholder: "Chat", class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description, "Description de l'article", class: "infoadd" %> </br>
  <%= form.text_field :description, placeholder: "Super photo de chat", class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :price, "Prix en euros", class: "infoadd" %> </br>
  <%= form.number_field :price,placeholder: "30", step: 0.01, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :avatar, "Uploader l'avatar", class: "infoadd" %> </br>
  <%= form.file_field :avatar, class: "" %>
</div>

<%= form.submit "Créer l'article", class:"btn-primary-add" %>

<% end %>
</div>

<%=render 'layouts/footer' %>

app/views/articles/show.html.erb
<%=render 'layouts/navbar' %>

<div class="article-show-container">
  <!-- Image du produit -->
  <div class="article-image">
    <%if @article.avatar.attached?%>
      <%= image_tag @article.avatar, alt: 'avatar', class: 'img-article'%>
    <%else%>
      <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
    <%end%>
  </div>

  <!-- Détails du produit -->
  <div class="article-details">
    <p class="article-name-show"><%= @article.name %></p>
    <p class="article-description"><%= @article.description %></p>
  
    <div class="article-price">
      <div class="size">
        <%= image_tag 'size.png', alt: 'size', class: 'size-icon' %>
        <p class="text-size">60x40</p>
      </div>
      <span class="price-article-show"><%= @article.price %>€</span>
    </div>
   

<%= form_with url: add_article_to_cart_cart_path(article_id: @article.slug), method: :post, class: 'article-form' do |f| %>
  <div class="input-quantity">
    <input 
  type="number" 
  name="quantity" 
  value="1"
  placeholder="Quantité"  
  class="quantity-input"
  oninput="this.value = this.value.replace(/[^0-9]/g, '')"
>
<div class="info-stock">
   <%= image_tag 'ok.png', alt: 'coche', class: 'coche-img' %>
   <p class="stock">En Stock</p>
</div>
  </div>
  <%= f.submit 'Ajouter au panier', class: 'article-btn' %>
<% end %>

<div class="admin-delete"></div>
  <% if current_user.is_admin %>
  <%= button_to "Supprimer cet article", article_path(@article), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet article ?" }, class: "btn-delete-admin" %>
  <% end %>
</div>

  </div>
</div>




<div class="render_footer">
  <%=render 'layouts/footer' %>
</div>