config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'utilisateurs', path_names: {
    sign_in: 'connexion',
    sign_up: 'inscription'
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, path: 'produits'


  resource :cart, only: [:show] do
    post 'add_article_to_cart', on: :collection
    delete 'remove_article_from_cart', on: :collection  # Suppression d'un article spécifique du panier
    delete 'clear_cart', on: :collection 
  end

scope '/checkout' do
  post 'create', to: 'checkout#create', as: 'checkout_create'
  get 'success', to: 'checkout#success', as: 'checkout_success'
  get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get '/contact', to: 'static_pages#contact'

  resources :profiles, only: [:show]
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user                       # Le panier appartient à un User.
  has_many :cart_items                   # Les items dans le panier.
  has_many :articles, through: :cart_items # Les articles dans le panier via cart_items.
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart || current_user.create_cart
    @cart_items = @cart.cart_items.includes(:article)

    # Supprimer les cart_items sans article associé
    @cart_items.each do |cart_item|
    cart_item.destroy if cart_item.article.nil?
  end
    
  @order = current_user.orders.last

  end


  def add_article_to_cart
    article = Article.find_by!(slug: params[:article_id])
    quantity = params[:quantity].to_i # Récupère la quantité envoyée
    quantity = 1 if quantity <= 0 # Définit une quantité minimale de 1
  
    @cart = current_user.cart || current_user.create_cart
    @cart_item = @cart.cart_items.find_or_create_by(article: article)
  
    # Ajoute la quantité spécifiée
    @cart_item.increment(:quantity, quantity)
    @cart_item.save
  
    flash[:notice] = "#{quantity} article(s) ajouté(s) au panier."
    redirect_to root_path
  end

 
  
  

  def remove_article_from_cart
    article = Article.find(params[:article_id]) 
    @cart = current_user.cart
    cart_item = @cart.cart_items.find_by(article: article)

    if cart_item
      if cart_item.quantity > 1
        cart_item.decrement(:quantity)
        cart_item.save
        flash[:notice] = "La quantité de l'article a été réduite."
      else
        cart_item.destroy 
        flash[:notice] = "L'article a été supprimé du panier."
      end
    else
      flash[:alert] = "Cet article n'est pas dans votre panier."
    end

    redirect_to cart_path
  end

  def clear_cart
    @cart = current_user.cart
    @cart.cart_items.destroy_all 
    flash[:notice] = "Votre panier a été vidé."
    redirect_to cart_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<%= render 'layouts/navbar' %>


<div class="container-title-panier">
<%= image_tag 'panier.png', alt: 'Panier', class: 'panierImgTitle' %>
<h2 class="panierTitle">
  Mon Panier
</h2>
</div>

<div class="articlepanier">
  <% if @cart_items.any? %>
  <div class="article-cart">
      <% @cart_items.each do |cart_item| %>

         <div class="articleshowpanier">
        <div class="imgTilteArticle">
          <%if cart_item.article.avatar.attached?%>
          <%= image_tag cart_item.article.avatar, alt: 'avatar', class: 'imgArticlePanier'%>
          <%else%>
          <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
          <%end%>
          <p class="nameArticle"><%= cart_item.article.name %></p>
        </div>

        <div class="containerInfo">
          <div class="infoArticlePanier">
            <p>Quantité : <%= cart_item.quantity %></p>
            <p class="priceArticle"><%= cart_item.article.price %>€</p>
          </div>

          <%= button_to remove_article_from_cart_cart_path(article_id: cart_item.article.id), method: :delete, class: "deleteBtn", style: "cursor: pointer;" do %>
            <%= image_tag("corbeille.png", alt: "Supprimer", class: "delete-icon") %>
          <% end %>
        </div>
        </div>
      <% end %>
     </div>


    <div class="trait"></div>

    <div class="containerTotal">
      <p class="textPanier">Total:</p>
      <div class="total">
        <p>Quantité : <%= @cart_items.sum { |item| item.quantity } %></p>
        <p class="priceArticle">
         <%= (@cart_items.sum { |item| item.quantity * item.article.price } * 100).ceil / 100.0 %> €
        </p>

      </div>
    </div>

    <div class="trait"></div>

    <div class="detail">
      <p class="textPanier">Livraison:</p>
      <p class="emailUser"><%= current_user.email %></p>
    </div>
   <%= button_to "Payer",
              checkout_create_path(total: @cart_items.sum { |item| item.quantity * item.article.price }),
              class: "payoutBtn",
              data: { turbo: false } %>

    <%= button_to 'Vider le panier', clear_cart_cart_path, method: :delete, class: "delete-panier", style: "cursor: pointer;" %>
   
  </div>
  <% else %>
    <p>Votre panier est vide.</p>
    
  <% end %>
</div>
<div class="footer_cart">
  <%=render 'layouts/footer' %>
</div>