config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'utilisateurs', path_names: {
    sign_in: 'connexion',
    sign_up: 'inscription'
}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles, path: 'produits'


  resource :cart, only: [:show] do
    post 'add_article_to_cart', on: :collection
    delete 'remove_article_from_cart', on: :collection  # Suppression d'un article spécifique du panier
    delete 'clear_cart', on: :collection 
  end

scope '/checkout' do
  post 'create', to: 'checkout#create', as: 'checkout_create'
  get 'success', to: 'checkout#success', as: 'checkout_success'
  get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  get '/contact', to: 'static_pages#contact'

  resources :profiles, only: [:show]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="upper-line">
    <%= image_tag 'logo.png', alt: 'Logo', class: 'logo-footer' %>
    <%= link_to 'Contact', contact_path, class: 'link-footer' %>
  </div>

  <div class="lower-line">
    <p class="copyright-container">© 2024 The cat. Tous droits réservés.</p>
    <div class="payment-icons">
    <%= image_tag 'mastercard.png', alt: 'Mastercard', class: 'icon-footer' %>
    <%= image_tag 'visa.png', alt: 'Visa', class: 'icon-footer' %>
    </div>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<nav>
  <%= link_to root_path, class: 'linknav' do %>
  <%= image_tag 'logo.png', alt: 'Accueil', class: 'logonav' %>
  <% end %>
  <div class="containerLink">
    <%= link_to 'Accueil', root_path, class: 'linknav' %>
    <div class="linkuser">
     <% if current_user%>
     <%= form_with url: profile_path(current_user.id), method: :get, class: 'logout-form' do %>
     <%= button_tag type: 'submit', class: 'btn-logout' do %>
     <%= image_tag 'profiluser.png', alt: 'Déconnexion', class: 'btnnav-icon' %>
     <% end %>
     <% end %>
    
     <%= form_with url: destroy_user_session_path, method: :delete, class: 'logout-form' do %>
     <%= button_tag type: 'submit', class: 'btn-logout' do %>
     <%= image_tag 'disconnect.png', alt: 'Déconnexion', class: 'btnnav-icon' %>
     <% end %>
     <% end %>
     <%else%>
     <%= button_to 'Se connecter', new_user_session_path, method: :get, class: 'btn-log' %>
     <% end %>
    </div>
  </div>
  <%= button_to cart_path, method: :get, class: 'btn-panier' do %>
  Panier
  <%= image_tag 'panier.png', alt: 'Panier', class: 'panier-icon' %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Market Cat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://js.stripe.com/v3/"></script>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == "notice" ? "success" : "danger" %>">
    <%= message %>
    </div>
    <% end %>

    <%= yield %>

  </body>
</html>